[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
game = { version = "0.1", path = "../game" }
cgpu = { version = "0.1", path = "../cgpu" }
nalgebra = { version = "0.33.2", features = ["convert-bytemuck"] }
wgpu = "22.1.0"
# cvk = { version = "0.1", path = "../cvk" }
winit = "0.30.5"
pollster = "0.4.0"
log = "0.4.22"
env_logger = "0.11.5"

egui = "0.29.1"
egui-wgpu = { version = "0.29.1", features = ["winit"] }
egui-winit = "0.29.1"
