[package]
name = "glyphers_ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "glyphers"
crate-type = ["cdylib"]

[dependencies]
liverking = { version = "*", path = "../liverking"  }
glyphers = { version="*", path="../glyphers" }