[package]
name = "liverking"
version = "0.1.0"
edition = "2021"
authors = [ "Sebastian Strobl" ]
license = "Apache-2.0"
repository = "https://github.com/TriedAngle/Cuber"
description = "Rust For The Primal Man"
readme = "README.md"
