[package]
name = "glyphers"
version = "0.1.0"
edition = "2021"

[dependencies]
liverking = { path = "../liverking", version = "*" }
fontdue = "0.7.3"
unicode-segmentation = "1.10.1"

[dev-dependencies]
image = "0.24.7"