[package]
name = "glyphers_test"
version = "0.1.0"
edition = "2021"

[dependencies]
liverking = { version = "*", path="../../liverking" }
glyphers = { version = "*", path="../../glyphers" }
glutin = "0.28"
glow = "0.12.3"
fontdue = "0.7.3"
image = "0.24.7"
unicode-segmentation = "1.10.1"